### ISSUE TITLE
Feature Request: read all records in the store

### ISSUE THREAD

**Issue by morshedrazm** [nwestfall/BlazorDB#4]
Thank you for your great library.

Would it be possible to have a method for getting all records of a store?
getting records one by one with GetRecordByIdAsync is time-consuming for big stores.

Thanks.

**Comment by nwestfall** [comment]
There actually is already a call on the manager called `ToArray<T>(string storeName)` that you should be able to use.

**Comment by morshedrazm** [comment]
It worked perfectly for me.

Thanks
